$$f(w_1, w_2) = 0.1w_1^2 + 2w_2^2 \;\;\;\;\;\;\;(1)$$

In [16]:
import numpy as np

In [17]:
def df_w(W):
    """
    Thực hiện tính gradient của dw1 và dw2
    Arguments:
    W -- np.array [w1, w2]
    Returns:
    dW -- np.array [dw1, dw2], array chứa giá trị đạo hàm theo w1 và w2
    """
    #################### YOUR CODE HERE ####################
    w1, w2 = W
    dw1 = 0.2 * w1
    dw2 = 4 * w2
    dW = np.array([dw1, dw2])
    ########################################################

    return dW

In [18]:
def Adam(W, dW, lr, V, S, beta1, beta2, t):
    """
    Thực hiện thuật tóan Adam để update w1 và w2
    Arguments:
    W -- np.array: [w1, w2]
    dW -- np.array: [dw1, dw2], array chứa giá trị đạo hàm theo w1 và w2
    lr -- float: learning rate
    V -- np.array: [v1, v2] Exponentially weighted averages gradients
    S -- np.array: [s1, s2] Exponentially weighted averages bình phương gradients
    beta1 -- float: hệ số long-range average cho V
    beta2 -- float: hệ số long-range average cho S
    t -- int: lần thứ t update (bắt đầu bằng 1)
    Returns:
    W -- np.array: [w1, w2] w1 và w2 sau khi đã update
    V -- np.array: [v1, v2] Exponentially weighted averages gradients sau khi đã cập nhật
    S -- np.array: [s1, s2] Exponentially weighted averages bình phương gradients sau khi đã cập nhật
    """
    epsilon = 1e-6
    #################### YOUR CODE HERE ####################
    V = beta1 * V + (1 - beta1) * dW
    S = beta2 * S + (1 - beta2) * dW**2
    V_corr = V / (1 - beta1**t)
    S_corr = S / (1 - beta2**t)
    W = W - lr * V_corr / np.sqrt(S_corr + epsilon)
    ########################################################
    return W, V, S

In [19]:
def train_p1(optimizer, lr, epochs):
    """
    Thực hiện tìm điểm minimum của function (1) dựa vào thuật toán
    được truyền vào từ optimizer
    Arguments:
    optimize : function thực hiện thuật toán optimization cụ thể
    lr -- float: learning rate
    epochs -- int: số lượng lần (epoch) lặp để tìm điểm minimum
    Returns:
    results -- list: list các cặp điểm [w1, w2] sau mỗi epoch (mỗi lần cập nhật)
    """
    # initial
    W = np.array([-5, -2], dtype=np.float32)
    V = np.array([0, 0], dtype=np.float32)
    S = np.array([0, 0], dtype=np.float32)
    results = [W]
    #################### YOUR CODE HERE ####################
    # Tạo vòng lặp theo số lần epochs
    # tìm gradient dW gồm dw1 và dw2
    # dùng thuật toán optimization cập nhật w1, w2, s1, s2, v1, v2
    # append cặp [w1, w2] vào list results
    # các bạn lưu ý mỗi lần lặp nhớ lấy t (lần thứ t lặp) và t bất đầu bằng 1
    for epoch in range(epochs):
        dW = df_w(W)
        W, V, S = optimizer(W, dW, lr, V, S, beta1 = 0.9, beta2 = 0.999, t = epoch + 1)
        results.append(W)
    ########################################################
    return results

In [20]:
train_p1(Adam, lr=0.2, epochs=30)

[array([-5., -2.], dtype=float32),
 array([-4.8, -1.8], dtype=float32),
 array([-4.6002545, -1.6008244], dtype=float32),
 array([-4.400948 , -1.4031725], dtype=float32),
 array([-4.202277 , -1.2078781], dtype=float32),
 array([-4.00445  , -1.0159273], dtype=float32),
 array([-3.8076859, -0.8284729], dtype=float32),
 array([-3.6122167 , -0.64684147], dtype=float32),
 array([-3.4182856 , -0.47252753], dtype=float32),
 array([-3.2261467, -0.3071692], dtype=float32),
 array([-3.036065  , -0.15249841], dtype=float32),
 array([-2.8483162 , -0.01026312], dtype=float32),
 array([-2.6631846 ,  0.11787565], dtype=float32),
 array([-2.4809632 ,  0.23046172], dtype=float32),
 array([-2.301952 ,  0.3263588], dtype=float32),
 array([-2.1264565 ,  0.40484202], dtype=float32),
 array([-1.9547864 ,  0.46564966], dtype=float32),
 array([-1.7872528,  0.508988 ], dtype=float32),
 array([-1.6241664 ,  0.53549445], dtype=float32),
 array([-1.4658347,  0.5461714], dtype=float32),
 array([-1.3125597,  0.54230