$$f(w_1, w_2) = 0.1w_1^2 + 2w_2^2 \;\;\;\;\;\;\;(1)$$

In [1]:
import numpy as np

In [2]:
def df_w(W):
    """
    Thực hiện tính gradient của dw1 và dw2
    Arguments:
    W -- np.array [w1, w2]
    Returns:
    dW -- np.array [dw1, dw2], array chứa giá trị đạo hàm theo w1 và w2
    """
    #################### YOUR CODE HERE ####################
    w1, w2 = W
    dw1 = 0.2 * w1
    dw2 = 4 * w2
    dW = np.array([dw1, dw2])
    ########################################################

    return dW

In [3]:
def sgd(W, dW, lr):
    """
    Thực hiện thuật toán Gradient Descent để update w1 và w2
    Arguments:
    W -- np.array: [w1, w2]
    dW -- np.array: [dw1, dw2], array chứa giá trị đạo hàm theo w1 và w2
    lr -- float: learning rate
    Returns:
    W -- np.array: [w1, w2] w1 và w2 sau khi đã update
    """
    #################### YOUR CODE HERE ####################


    W = W - dW * lr
    ########################################################
    return W

In [6]:
def train_p1(optimizer, lr, epochs):
    """
    Thực hiện tìm điểm minimum của function (1) dựa vào thuật toán
    được truyền vào từ optimizer
    Arguments:
    optimize : function thực hiện thuật toán optimization cụ thể
    lr -- float: learning rate
    epoch -- int: số lượng lần (epoch) lặp để tìm điểm minimum
    Returns:
    results -- list: list các cặp điểm [w1, w2] sau mỗi epoch (mỗi lần cập nhật)
    """

    # initial point
    W = np.array([-5, -2], dtype=np.float32)
    # list of results
    results = [W]
    #################### YOUR CODE HERE ####################
    # Tạo vòng lặp theo số lần epochs
    # tìm gradient dW gồm dw1 và dw2
    # dùng thuật toán optimization cập nhật w1 và w2
    # append cặp [w1, w2] vào list results
    for _ in range(epochs):
        dW = df_w(W)
        W = optimizer(W, dW, lr)
        results.append(W)
    ########################################################
    return results

In [7]:
train_p1(sgd, lr=0.4, epochs=30)

[array([-5., -2.], dtype=float32),
 array([-4.6,  1.2], dtype=float32),
 array([-4.232, -0.72 ], dtype=float32),
 array([-3.8934398 ,  0.43200004], dtype=float32),
 array([-3.5819645 , -0.25920004], dtype=float32),
 array([-3.2954073 ,  0.15552002], dtype=float32),
 array([-3.0317748 , -0.09331201], dtype=float32),
 array([-2.7892327 ,  0.05598721], dtype=float32),
 array([-2.5660942 , -0.03359233], dtype=float32),
 array([-2.3608067,  0.0201554], dtype=float32),
 array([-2.1719422 , -0.01209324], dtype=float32),
 array([-1.9981868 ,  0.00725594], dtype=float32),
 array([-1.8383319 , -0.00435357], dtype=float32),
 array([-1.6912653 ,  0.00261214], dtype=float32),
 array([-1.5559641 , -0.00156728], dtype=float32),
 array([-1.4314870e+00,  9.4037014e-04], dtype=float32),
 array([-1.316968e+00, -5.642221e-04], dtype=float32),
 array([-1.2116106e+00,  3.3853325e-04], dtype=float32),
 array([-1.1146817e+00, -2.0311994e-04], dtype=float32),
 array([-1.0255072e+00,  1.2187197e-04], dtype=floa