$$f(w_1, w_2) = 0.1w_1^2 + 2w_2^2 \;\;\;\;\;\;\;(1)$$

In [35]:
import numpy as np

In [36]:
def df_w(W):
    """
    Thực hiện tính gradient của dw1 và dw2
    Arguments:
    W -- np.array [w1, w2]
    Returns:
    dW -- np.array [dw1, dw2], array chứa giá trị đạo hàm theo w1 và w2
    """
    #################### YOUR CODE HERE ####################
    w1, w2 = W
    dw1 = 0.2 * w1
    dw2 = 4 * w2
    dW = np.array([dw1, dw2])
    ########################################################

    return dW

In [ ]:
def sgd_momentum(W, dW, lr, V, beta = 0.9):
    """
    Thực hiện thuật tóan Gradient Descent + Momentum để update w1 và w2
    Arguments:
    W -- np.array: [w1, w2]
    dW -- np.array: [dw1, dw2], array chứa giá trị đạo hàm theo w1 và w2
    lr -- float: learning rate
    V -- np.array: [v1, v2] Exponentially weighted averages gradients
    beta -- float: hệ số long-range average
    Returns:
    W -- np.array: [w1, w2] w1 và w2 sau khi đã update
    V -- np.array: [v1, v2] Exponentially weighted averages gradients sau khi đã cập nhật
    """
    #################### YOUR CODE HERE ####################

    V = beta * V + (1 - beta) * W
    W = W - lr * V
    ########################################################
    return W, V

In [38]:
def train_p1(optimizer, lr, epochs):
    """
    Thực hiện tìm điểm minimum của function (1) dựa vào thuật toán được truyền vào từ optimizer
    Arguments:
    optimize : function thực hiện thuật toán optimization cụ thể
    lr -- float: learning rate
    epochs -- int: số lượng lần (epoch) lặp để tìm điểm minimum
    Returns:
    results -- list: list các cặp điểm [w1, w2] sau mỗi epoch (mỗi lần cập nhật)
    """
    # initial
    W = np.array([-5, -2], dtype=np.float32)
    V = np.array([0, 0], dtype=np.float32)
    results = [W]
    #################### YOUR CODE HERE ####################
    # Tạo vòng lặp theo số lần epochs
    # tìm gradient dW gồm dw1 và dw2
    # dùng thuật toán optimization cập nhật w1, w2, v1, v2
    # append cặp [w1, w2] vào list results
    for _ in range(epochs):
        dW = df_w(W)
        W, V = optimizer(W, dW, lr, V)
        results.append(W)

    ########################################################
    return results

In [39]:
train_p1(sgd_momentum, lr=0.6, epochs=30)

[array([-5., -2.], dtype=float32),
 array([-4.7 , -1.88], dtype=float32),
 array([-4.148 , -1.6592], dtype=float32),
 array([-3.4023197, -1.3609279], dtype=float32),
 array([-2.5270684, -1.0108274], dtype=float32),
 array([-1.5877181, -0.6350874], dtype=float32),
 array([-0.6470398 , -0.25881606], dtype=float32),
 array([0.23839307, 0.09535706], dtype=float32),
 array([1.0209789 , 0.40839142], dtype=float32),
 array([1.6640475, 0.6656189], dtype=float32),
 array([2.1429663 , 0.85718644], dtype=float32),
 array([2.4454153 , 0.97816604], dtype=float32),
 array([2.5708945, 1.0283577], dtype=float32),
 array([2.529572 , 1.0118288], dtype=float32),
 array([2.3406074, 0.936243 ], dtype=float32),
 array([2.0301027 , 0.81204116], dtype=float32),
 array([1.6288425 , 0.65153706], dtype=float32),
 array([1.1699777 , 0.46799114], dtype=float32),
 array([0.6868007 , 0.27472034], dtype=float32),
 array([0.21073344, 0.0842934 ], dtype=float32),
 array([-0.23037109, -0.09214845], dtype=float32),
 arra